# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-05-29T17:17:31Z"
  generation: 2
  labels:
    app: modelinf-service
  name: modelinf-service
  namespace: default
  resourceVersion: "3514"
  uid: b0d8c754-7af3-49bd-8fb2-aec95a2a35b4
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: modelinf-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: modelinf-service
    spec:
      containers:
      - image: modelinfservice:1.0
        imagePullPolicy: IfNotPresent
        name: modelinfservice
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-05-29T17:17:31Z"
    lastUpdateTime: "2025-05-29T17:17:32Z"
    message: ReplicaSet "modelinf-service-656bc4b954" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-05-29T17:38:34Z"
    lastUpdateTime: "2025-05-29T17:38:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
