name: CI
on:
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build MpdelInfService and deploy to minikube
    steps:
    - uses: actions/checkout@v4
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Try the cluster!
      run: kubectl get pods -A
    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./ModelInfService/Dockerfile -t saniya-afreen/modelinf-service:latest .
        echo -n "verifying images:"
        docker images
    - name: Deploy Pods to minikube
      run:
        kubectl apply -f deployment/deployment.yml
    - name: Deploy Service to minikube
      run:
        kubectl apply -f deployment/service.yml
    - name: Test service URLs
      run: |
        minikube service list
        minikube service modelinf-service --url
        echo "------------------opening the service------------------"
        curl $(minikube service modelinf-service --url)
