name: CI
on:
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build MpdelInfService and deploy to minikube
    steps:
    - uses: actions/checkout@v4
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Try the cluster!
      run: kubectl get pods -A
    - name: Build image
      run: |
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t saniya-afree/modelinf-service:latest
        echo -n "verifying images:"
        docker images
    - name: Deploy to minikube
      run:
        kubectl apply -f deployment/modelinf-service-k8s.yaml
    - name: Test service URLs
      run: |
        minikube service list
        minikube service modelinf-service --url
        echo "------------------opening the service------------------"
        curl $(minikube service modelinf-service --url)
